### ISSUE TITLE
Running into validation error from pydantic

### ISSUE THREAD

**Issue by sanzgiri** [trancethehuman/spotify-chat#1]
I am getting the following error running the code. Python 3.9 on a Mac, latest versions of all packages in requirements.txt

```
Traceback (most recent call last):
  File "/Users/sanzgiri/spotify-chat/main.py", line 2, in <module>
    from ai_tools import music_player_tools
  File "/Users/sanzgiri/spotify-chat/ai_tools.py", line 21, in <module>
    def by_lyrics(lyrics: str) -> str:
  File "/Users/sanzgiri/miniconda3/envs/spangchain/lib/python3.9/site-packages/langchain/tools/base.py", line 767, in _make_tool
    return StructuredTool.from_function(
  File "/Users/sanzgiri/miniconda3/envs/spangchain/lib/python3.9/site-packages/langchain/tools/base.py", line 711, in from_function
    return cls(
  File "/Users/sanzgiri/miniconda3/envs/spangchain/lib/python3.9/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for StructuredTool
args_schema
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)
```

Would appreciate any help. Thanks!

**Comment by trancethehuman** [comment]
@sanzgiri hey this looks like a pydantic error. I'll take a look at some point but maybe check out this thread about LangChain moving to Pydantic 2: https://github.com/langchain-ai/langchain/issues/6841

**Comment by sanzgiri** [comment]
Hi @trancethehuman - thanks for the pointers. The app works for me if I replace `pydantic` with `pydantic.v1` on line 1 in `ai_tools.py`
